language: java
jdk: oraclejdk8

sudo: required

services:
  - docker

after_success:
  - if [  "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker login -u="mattcopas" -p="$DOCKER_PASSWORD" &&
    ./gradlew incrementPatchVersion &&
    git add build.gradle &&
    git commit -m "Travis Version Increment [ci skip]" &&
    git push https://mattcopas:$GITHUB_TOKEN@github.com/mattcopas/financeapp-data-service.git HEAD:develop &&
    gradle buildDocker &&
    docker push mattcopas/financeapp-data-service &&
    fi

notifications:
  email:
    on_success: never
    on_failure: never
