language: java
jdk: oraclejdk8

sudo: required

services:
  - docker

after_success:
  - echo "Travis branch"
  - echo "$TRAVIS_BRANCH"
  - if [  "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker login -u="mattcopas" -p="$DOCKER_PASSWORD";
    gradle buildDocker;
    docker push mattcopas/financeapp-data-service;
    fi

notifications:
  email:
    on_success: never
    on_failure: never