---
server:
  port: 8081

---
spring.profiles: dev

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    hibernate.ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/financedataservicedb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

  hibernate:


---
spring.profiles: tdd

