---
server:
  port: 8081

allowedOrigin: 'http://localhost:3000'

---
spring.profiles: docker

allowedOrigin: ${ALLOWED_ORIGIN}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    hibernate.ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring.profiles: dev

allowedOrigin: 'http://localhost:3000'

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    hibernate.ddl-auto: create

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/financedataservicedb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password


---
spring.profiles: tdd

#security:
#  ignored: /**